# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Unit Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest black pip-audit
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics --ignore D203
    - name: Check code formatting with black
      run: |
        # Black will return an error if it finds formatting issues
        python -m black dorothy --line-length 120 --check
    - name: Run pip-audit to scan requirements.txt for packages with known vulnerabilities
      run: |
        # pip-audit will return exit code 0 if no vulnerabilities are found
        python -m pip-audit --requirement requirements.txt
    - name: Start Dorothy
      run: |
        # Check if Dorothy can start without exceptions
        python -m dorothy --help
#    - name: Test with pytest
#       run: |
#         pytest
